# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [3]:
splits = s.split(' ')
print(splits)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
formatted = 'The diameter of {} is {} kilometers.'.format(planet,diameter)
print(formatted)

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [5]:
hellofound = d['k1'][3]['tricky'][3]['target'][3]
print(hellofound)

hello

# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [13]:
arr = np.zeros(10)
print("4.1 Array of 10 zeros: " + str(arr))

4.1 Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [14]:
arr1 = np.ones(10)*5
print("4.2 Array of 10 fives: " + str(arr1))

4.2 Array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [15]:
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concat = np.concatenate((a, b), axis = 0)
print(concat)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd

In [23]:
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A)
print(df)

   0  1
0  3  3
1  1  5
2  4  0

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [24]:
dates = pd.date_range(start ='1-1-2023', end ='10-02-2023', freq ='1D')
print(dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [26]:
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24